title: Om Tiwari's Homepage
page-top-title: Om Tiwari
top-section-bg-text: Artificial Intelligence and Robotics
home-subtitle: Om TIwari&ensp;|&ensp;ओम तिवारी
copyright-text: '&copy; Om Tiwari 2025. All Rights Reserved.'
